### ISSUE TITLE
unhashable type: 'dict'

### ISSUE THREAD

**Issue by yadavayush0808** [Twingate-Labs/saml_service_provider#1]
while executing self.do_entity_descriptor(entity_descriptor) ,it is throwing the error unhashable type: 'dict'.
Any clue on this?

**Comment by emrul** [comment]
Hi @yadavayush0808 - let us look into this!

**Comment by inbalzelinger** [comment]
@yadavayush0808 Ill need some more details. Could you please attach the full stack trace?
maybe also your `entity_descriptor` object

**Comment by emrul** [comment]
Hi @yadavayush0808, just following up on this - are you still experiencing an issue and can you share a stack trace to assist @inbalzelinger? If we don't hear from you we will assume the issue is resolved and close the issue.
